routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');
Route::resource('customer','CustomerController')->middleware('auth');
Route::resource('bussiness','BussinessController')->middleware('auth');
Route::resource('provider','ProviderController')->middleware('auth');
Route::resource('sale','SaleController')->middleware('auth');
Route::resource('product','ProductController')->middleware('auth');
Route::resource('purchase','PurchaseController')->middleware('auth');
Route::resource('type_user','TypeUserController')->middleware('auth');
Route::resource('services','ServiceController')->middleware('auth');
Route::resource('operator','OperatorController')->middleware('auth');
Route::resource('quantity_session','QuantitySessionController')->middleware('auth');
Route::resource('typeTraetment','TypeTraetmentController')->middleware('auth');
Route::resource('traetment','TraetmentController')->middleware('auth');
Route::resource('sale_traetment','SaleTraetmentController')->middleware('auth');
Route::resource('traetment_process','TraetmentProcessController')->middleware('auth');
Route::resource('comision','CommissionController')->middleware('auth');
Route::resource('payment','PaymentController')->middleware('auth');
Route::resource('expense','ExpenseController')->middleware('auth');
Route::resource('users','UserController')->middleware('auth');

Route::get('event','EventController@index')->middleware('auth');
Route::get('cuadre','BoxController@cuadre_caja')->middleware('auth');
Route::get('listCuadre', 'BoxController@list_cuadre')->middleware('auth');
Route::get('descargar-venta/{id}','SaleController@imprimir');
Route::get('descargar-venta-tratamiento/{id}','SaleTraetmentController@imprimir');
Route::get('descargar-pago-tratamiento/{id}','SaleTraetmentController@pay');
Route::get('descargar-pago-venta/{id}','SaleTraetmentController@pay_sale');

Route::post('eventActividad','EventController@Ajax')->middleware('auth');
Route::resource('box','BoxController')->middleware('auth');

Route::get('cuadre_caja/{id}','BoxController@show_box')->name('mostrar');

app/Models/Expense.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Expense extends Model
{
    use HasFactory;

    protected $fillable = ['name','quantity','description'];
}

app/Http/Controllers/ExpenseController.php
<?php

namespace App\Http\Controllers;

use App\Models\Expense;
use App\Models\Cuadre;
use Illuminate\Http\Request;

class ExpenseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $cuadre = Cuadre::orderBy('id','desc')->first();
        $fecha_fin = $cuadre->end;
        $expenses = Expense::whereDate('created_at','>',$fecha_fin)->get();
        return view('expense.index',compact('expenses'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        Expense::create($request->all());
        return redirect ('expense');
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Expense  $expense
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $expense = Expense::findOrFail($id);
        $expense->update($request->all());
        return redirect('expense');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Expense  $expense
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $expense = Expense::findOrFail($id);
        $expense->delete();
        return redirect('expense');
    }
}

resources/views/expense/crear.blade.php
<div class="modal fade" id="createCustomer">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Gastos</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{route('expense.store')}}" method="post">
            @csrf
          <div class="mb-3">
            <label for="name" class="form-label">Nombre de Gasto</label>
            <input type="text" class="form-control" name="name" required>
          </div>
          <div class="mb-3">
            <label for="quantity" class="form-label">Cantidad</label>
            <input type="text" class="form-control" name="quantity" onkeypress="return validar(event);" required>
          </div>
          <div class="mb-3">
            <label for="description" class="form-label">Descripción</label>
            <textarea name="description" id="" cols="30" rows="2" class="form-control" required></textarea>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
              <button class="btn btn-primary">Guardar</button>
          </div>
          
        </form>
      </div>
    </div>
  </div>
</div>

resources/views/expense/delete.blade.php
<div class="modal fade" id="modal-delete-{{$expense->id}}">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-danger" >
                <h5 class="modal-title" id="exampleModalLabel">Gasto</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{{action('ExpenseController@destroy',$expense->id)}}" method="POST">
                    @csrf
                    <input name="_method" type="hidden" value="DELETE">
                    <p>Confirma que desea eliminar al Cliente {{$expense->name}} </p>
                        
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <button class="btn btn-primary">Confirmar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/expense/edit.blade.php
<div class="modal fade" id="editCustomer-{{$expense->id}}">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-warning" >
        <h5 class="modal-title" id="exampleModalLabel">Gasto</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{route('expense.update',$expense->id)}}" method="post">
        <input name="_method" type="hidden" value="PATCH">
            @csrf
          <div class="mb-3">
            <label for="fullname" class="form-label">Nombre Completo</label>
            <input type="text" class="form-control" name="fullname" value="{{$expense->name}}">
          </div>
          <div class="mb-3">
            <label for="address" class="form-label">Cantidad</label>
            <input type="text" class="form-control" name="quantity" value="{{$expense->quantity}}">
          </div>
          <div class="mb-3">
            <label for="phone" class="form-label">Descripción</label>
            <input type="text" class="form-control" name="description" value="{{$expense->description}}">
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
              <button class="btn btn-primary">Editar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

resources/views/expense/index.blade.php
@extends('layouts.admin')
@section('content')
<div style="background: white">
    @include('expense.crear')
    <hr><h2 class="text-center">Listado de Gastos<button data-bs-toggle="modal" data-bs-target="#createCustomer" class="btn btn-success rounded-circle text-white"><i class="fa fa-plus"></i></button></h2><hr>
    <table class="table text-center">
        @if(isset($expenses))
            <tr>
                <th>No.</th>
                <th>Nombre</th>
                <th>Cantidad</th>
                <th>Descripción</th>
                <th>Opciones</th>
            </tr>
            @foreach($expenses as $expense)
                <tr>
                    <td>{{$loop->iteration}}</td>
                    <td>{{$expense->name}}</td>
                    <td>{{$expense->quantity}}</td>
                    <td>{{$expense->description}}</td>
                    <td>
                        <a data-bs-toggle="modal" data-bs-target="#editCustomer-{{$expense->id}}" href="{{action('ExpenseController@edit', $expense->id)}}"><button data-bs-toggle="tooltip" data-bs-placement="top" title="Editar" aria-hidden="true" class="btn btn-info"><i class="fas fa-edit" aria-hidden="true"></i></button></a>
                        <a data-bs-toggle="modal" data-bs-target="#modal-delete-{{$expense->id}}" data-toggle="modal"><button data-bs-toggle="tooltip" data-bs-placement="top" title="Eliminar" class="btn btn-danger"><i class="fa fa-times" aria-hidden="true"></i> </button></a>   
                    </td>
                </tr>
                @include('expense.edit')
                @include('expense.delete')
            @endforeach
        @else
            <tr>
                <td>No Existen Registros</td>
            </tr>
        @endif
    </table>
</div>
@push('scripts')
<script>
function validar(evt)
  {
      var code = (evt.which) ? evt.which : evt.keyCode;
      if(code==8){
          return true;
      }else if(code>=46 && code<=57){
          return true;
      }else{
          return false;
      }
  }
</script>
@endpush
@endsection