routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');
Route::resource('customer','CustomerController')->middleware('auth');
Route::resource('bussiness','BussinessController')->middleware('auth');
Route::resource('provider','ProviderController')->middleware('auth');
Route::resource('sale','SaleController')->middleware('auth');
Route::resource('product','ProductController')->middleware('auth');
Route::resource('purchase','PurchaseController')->middleware('auth');
Route::resource('type_user','TypeUserController')->middleware('auth');
Route::resource('services','ServiceController')->middleware('auth');
Route::resource('operator','OperatorController')->middleware('auth');
Route::resource('quantity_session','QuantitySessionController')->middleware('auth');
Route::resource('typeTraetment','TypeTraetmentController')->middleware('auth');
Route::resource('traetment','TraetmentController')->middleware('auth');
Route::resource('sale_traetment','SaleTraetmentController')->middleware('auth');
Route::resource('traetment_process','TraetmentProcessController')->middleware('auth');
Route::resource('comision','CommissionController')->middleware('auth');
Route::resource('payment','PaymentController')->middleware('auth');
Route::resource('expense','ExpenseController')->middleware('auth');
Route::resource('users','UserController')->middleware('auth');

Route::get('event','EventController@index')->middleware('auth');
Route::get('cuadre','BoxController@cuadre_caja')->middleware('auth');
Route::get('listCuadre', 'BoxController@list_cuadre')->middleware('auth');
Route::get('descargar-venta/{id}','SaleController@imprimir');
Route::get('descargar-venta-tratamiento/{id}','SaleTraetmentController@imprimir');
Route::get('descargar-pago-tratamiento/{id}','SaleTraetmentController@pay');
Route::get('descargar-pago-venta/{id}','SaleTraetmentController@pay_sale');

Route::post('eventActividad','EventController@Ajax')->middleware('auth');
Route::resource('box','BoxController')->middleware('auth');

Route::get('cuadre_caja/{id}','BoxController@show_box')->name('mostrar');

app/Models/Operator.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Operator extends Model
{
    use HasFactory;

    protected $fillable = ['fullname','address','phone','profile_picture'];

    public function traetment_process(){
        return $this->belongsTo('App\Models\TraetmentProcess');
    }

    public function sale_traetment(){
        return $this->belongsTo('App\Models\SaleTraetment');
    }
}

app/Http/Controllers/OperatorController.php
<?php

namespace App\Http\Controllers;

use App\Models\Operator;
use Illuminate\Http\Request;

class OperatorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $operators = Operator::all();
        return view('operator.index',compact('operators'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        Operator::create($request->all());
        return redirect('operator');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Operator  $operator
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $operator = Operator::findOrFail($id);
        $operator->update($request->all());
        return redirect('operator');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Operator  $operator
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $operator = Operator::findOrFail($id);
        $operator->delete();
        return redirect('operator');
    }
}

resources/views/operator/crear.blade.php
<div class="modal fade" id="createOperator">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Operador</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{route('operator.store')}}" method="post">
            @csrf
          <div class="mb-3">
            <label for="fullname" class="form-label">Nombre Completo</label>
            <input type="text" class="form-control" name="fullname">
          </div>
          <div class="mb-3">
            <label for="address" class="form-label">Dirección</label>
            <input type="text" class="form-control" name="address">
          </div>
          <div class="mb-3">
            <label for="phone" class="form-label">Teléfono</label>
            <input type="text" class="form-control" name="phone">
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
              <button class="btn btn-primary">Guardar</button>
          </div>
          
        </form>
      </div>
    </div>
  </div>
</div>

resources/views/operator/delete.blade.php
<div class="modal fade" id="modal-delete-{{$operator->id}}">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-danger" >
                <h5 class="modal-title" id="exampleModalLabel">Operador</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{{action('OperatorController@destroy',$operator->id)}}" method="POST">
                    @csrf
                    <input name="_method" type="hidden" value="DELETE">
                    <p>Confirma que desea eliminar al Operador {{$operator->fullname}} </p>
                        
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <button class="btn btn-primary">Confirmar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/operator/edit.blade.php
<div class="modal fade" id="editOperator-{{$operator->id}}">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-warning" >
        <h5 class="modal-title" id="exampleModalLabel">Operador</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{route('operator.update',$operator->id)}}" method="post">
        <input name="_method" type="hidden" value="PATCH">
            @csrf
          <div class="mb-3">
            <label for="fullname" class="form-label">Nombre Completo</label>
            <input type="text" class="form-control" name="fullname" value="{{$operator->fullname}}">
          </div>
          <div class="mb-3">
            <label for="address" class="form-label">Dirección</label>
            <input type="text" class="form-control" name="address" value="{{$operator->address}}">
          </div>
          <div class="mb-3">
            <label for="phone" class="form-label">Teléfono</label>
            <input type="text" class="form-control" name="phone" value="{{$operator->phone}}">
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
              <button class="btn btn-primary">Editar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

resources/views/operator/index.blade.php
@extends('layouts.admin')
@section('content')
<div style="background: white">
    @include('operator.crear')
    <hr><h2 class="text-center">Listado de Operadores  <button data-bs-toggle="modal" data-bs-target="#createOperator" class="btn btn-success rounded-circle text-white"><i class="fa fa-plus"></i></button></h2><hr>
    <table class="table text-center">
        @if(isset($operators))
            <tr>
                <th>No.</th>
                <th>Nombre</th>
                <th>Dirección</th>
                <th>Teléfono</th>
                <th>Opciones</th>
            </tr>
            @foreach($operators as $operator)
                <tr>
                    <td>{{$loop->iteration}}</td>
                    <td>{{$operator->fullname}}</td>
                    <td>{{$operator->address}}</td>
                    <td>{{$operator->phone}}</td>
                    <td>
                        <a data-bs-toggle="modal" data-bs-target="#editOperator-{{$operator->id}}" href="{{action('OperatorController@edit', $operator->id)}}"><button data-bs-toggle="tooltip" data-bs-placement="top" title="Editar" aria-hidden="true" class="btn btn-info"><i class="fas fa-edit" aria-hidden="true"></i></button></a>
                        @if(Auth::user()->type_user->name == 'admin')
                        <a data-bs-toggle="modal" data-bs-target="#modal-delete-{{$operator->id}}" data-toggle="modal"><button data-bs-toggle="tooltip" data-bs-placement="top" title="Eliminar" class="btn btn-danger"><i class="fa fa-times" aria-hidden="true"></i> </button></a>   
                        @endif
                    </td>
                </tr>
                @include('operator.edit')
                @include('operator.delete')
            @endforeach
        @else
            <tr>
                <td>No Existen Registros</td>
            </tr>
        @endif
    </table>
</div>
@endsection