routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');
Route::resource('customer','CustomerController')->middleware('auth');
Route::resource('bussiness','BussinessController')->middleware('auth');
Route::resource('provider','ProviderController')->middleware('auth');
Route::resource('sale','SaleController')->middleware('auth');
Route::resource('product','ProductController')->middleware('auth');
Route::resource('purchase','PurchaseController')->middleware('auth');
Route::resource('type_user','TypeUserController')->middleware('auth');
Route::resource('services','ServiceController')->middleware('auth');
Route::resource('operator','OperatorController')->middleware('auth');
Route::resource('quantity_session','QuantitySessionController')->middleware('auth');
Route::resource('typeTraetment','TypeTraetmentController')->middleware('auth');
Route::resource('traetment','TraetmentController')->middleware('auth');
Route::resource('sale_traetment','SaleTraetmentController')->middleware('auth');
Route::resource('traetment_process','TraetmentProcessController')->middleware('auth');
Route::resource('comision','CommissionController')->middleware('auth');
Route::resource('payment','PaymentController')->middleware('auth');
Route::resource('expense','ExpenseController')->middleware('auth');
Route::resource('users','UserController')->middleware('auth');

Route::get('event','EventController@index')->middleware('auth');
Route::get('cuadre','BoxController@cuadre_caja')->middleware('auth');
Route::get('listCuadre', 'BoxController@list_cuadre')->middleware('auth');
Route::get('descargar-venta/{id}','SaleController@imprimir');
Route::get('descargar-venta-tratamiento/{id}','SaleTraetmentController@imprimir');
Route::get('descargar-pago-tratamiento/{id}','SaleTraetmentController@pay');
Route::get('descargar-pago-venta/{id}','SaleTraetmentController@pay_sale');

Route::post('eventActividad','EventController@Ajax')->middleware('auth');
Route::resource('box','BoxController')->middleware('auth');

Route::get('cuadre_caja/{id}','BoxController@show_box')->name('mostrar');

app/Models/Traetment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Traetment extends Model
{
    use HasFactory;

    protected $fillable = ['name','price_traetment','description','quantity_session_id','type_traetment_id'];

    public function quantity_session(){
        return $this->belongsTo('App\Models\QuantitySession');
    }

    public function type_traetment(){
        return $this->belongsTo('App\Models\TypeTraetment');
    }

    public function traetment_processes(){
        return $this->belongsTo('App\Models\TraetmentProcess');
    }
}

app/Http/Controllers/TraetmentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Traetment;
use App\Models\QuantitySession;
use App\Models\TypeTraetment;
use Illuminate\Http\Request;

class TraetmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $traetments = Traetment::all();
        $quantities = QuantitySession::all();
        $typesTraetments = TypeTraetment::all();
        return view('traetment.index',compact('traetments','quantities','typesTraetments'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        Traetment::create($request->all());
        return redirect('traetment');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Traetment  $traetment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $traetment = Traetment::findOrFail($id);
        $traetment->update($request->all());
        return redirect('traetment');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Traetment  $traetment
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $traetment = Traetment::findOrFail($id);
        $traetment->delete();
        return redirect('traetment');
    }
}

resources/views/traetment/crear.blade.php
<div class="modal fade" id="createTraetment">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Tratamiento</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{route('traetment.store')}}" method="post">
            @csrf
          <div class="mb-3">
            <label for="name" class="form-label">Nombre de Tratamiento</label>
            <input type="text" class="form-control" name="name" required>
          </div>
          <div class="mb-3">
            <label for="price_traetment" class="form-label">Precio</label>
            <input type="text" class="form-control" onkeypress="return validar(event);" name="price_traetment" required>
          </div>
          <div class="mb-3">
            <label for="quantity_session_id" class="form-label">Período de Tiempo</label>
            <select name="quantity_session_id" id="quantity_session_id" class="form-control" required>
              <option disabled selected value="">--Elegir un Periodo--</option>
              @foreach($quantities as $quantity)
                <option value="{{$quantity->id}}">{{$quantity->quantity_session}} - {{$quantity->time_frame}}</option>
              @endforeach
            </select>
          </div>
          <div class="mb-3">
            <label for="type_traetment_id" class="form-label">Tipo de Tratamiento</label>
            <select name="type_traetment_id" id="type_traetment_id" class="form-control" required>
              <option disabled selected value="">--Tipo de Tratamiento--</option>
              @foreach($typesTraetments as $types)
                <option value="{{$types->id}}">{{$types->name}}</option>
              @endforeach
            </select>
          </div>
          <div class="mb-3">
            <label for="description" class="form-label">Descripción</label>
            <textarea name="description" id="description" cols="30" rows="2" class="form-control"></textarea>
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
              <button class="btn btn-primary">Guardar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

resources/views/traetment/delete.blade.php
<div class="modal fade" id="modal-delete-{{$traetment->id}}">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-danger">
                <h5 class="modal-title" id="exampleModalLabel">Servicios</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{{action('TraetmentController@destroy',$traetment->id)}}" method="POST">
                    @csrf
                    <input name="_method" type="hidden" value="DELETE">
                    <p>Confirma que desea eliminar el Servicio {{$traetment->name}} </p>
                        
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <button class="btn btn-primary">Confirmar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/traetment/edit.blade.php
<div class="modal fade" id="editTraetment-{{$traetment->id}}">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-warning" >
        <h5 class="modal-title" id="exampleModalLabel">Tratamiento</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{route('traetment.update',$traetment->id)}}" method="post">
        <input name="_method" type="hidden" value="PATCH">
            @csrf
            <div class="mb-3">
              <label for="name" class="form-label">Nombre de Servicio</label>
              <input type="text" class="form-control" name="name" value="{{$traetment->name}}">
            </div>
            <div class="mb-3">
              <label for="price_traetment" class="form-label">Precio</label>
              <input type="text" class="form-control" name="price_traetment" onkeypress="return validar(event);" value="{{$traetment->price_traetment}}">
            </div>
            <div class="mb-3">
              <label for="quantity_session_id" class="form-label">Período de Tiempo</label>
              <select name="quantity_session_id" id="quantity_session_id" class="form-control">
                <option disabled selected>--Elegir un Periodo--</option>
                @foreach($quantities as $quantity)
                  <option value="{{$quantity->id}}"{{($quantity->id == $traetment->quantity_session_id) ? 'selected' : ''}}>{{$quantity->quantity_session}} - {{$quantity->time_frame}}</option>
                @endforeach
              </select>
            </div>
            <div class="mb-3">
              <label for="description" class="form-label">Descripción</label>
              <textarea name="description" id="description" cols="30" rows="10" class="form-control">{{$traetment->description}}</textarea>
            </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
              <button class="btn btn-primary">Editar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

resources/views/traetment/index.blade.php
@extends('layouts.admin')
@section('content')
<div style="background: white">
    @include('traetment.crear')
    <hr><h2 class="text-center">Listado de Tratamientos  <button data-bs-toggle="modal" data-bs-target="#createTraetment" class="btn btn-success rounded-circle text-white"><i class="fa fa-plus"></i></button></h2><hr>
    <input type="text" class="form-control" id="searchTraetment" placeholder="Tratamiento a Buscar">
    <table class="table text-center" id="tableData">
        @if(isset($traetments)) 
            <tr>
                <th>No.</th>
                <th>Tratamiento</th>
                <th>Precio</th>
                <th>C. de Sesiones</th>
                <th>Tipo de Tratamiento</th>
                <th>Descripción</th>
            </tr>
            @foreach($traetments as $traetment)
                <tr>
                    <td>{{$loop->iteration}}</td>
                    <td>{{$traetment->name}}</td>
                    <td>Q.{{number_format($traetment->price_traetment,2)}}</td>
                    <td>{{$traetment->quantity_session->quantity_session}} - {{$traetment->quantity_session->time_frame}}</td>
                    <td>{{$traetment->type_traetment->name}}</td>
                    <td>{{$traetment->description}}</td>
                    <td>
                        <a data-bs-toggle="modal" data-bs-target="#editTraetment-{{$traetment->id}}" href="{{action('TraetmentController@edit', $traetment->id)}}"><button data-bs-toggle="tooltip" data-bs-placement="top" title="Editar" aria-hidden="true" class="btn btn-info"><i class="fas fa-edit" aria-hidden="true"></i></button></a>
                        <a data-bs-toggle="modal" data-bs-target="#modal-delete-{{$traetment->id}}" data-toggle="modal"><button data-bs-toggle="tooltip" data-bs-placement="top" title="Eliminar" class="btn btn-danger"><i class="fa fa-times" aria-hidden="true"></i> </button></a>   
                    </td>
                </tr>
                @include('traetment.edit')
                @include('traetment.delete')
            @endforeach
        @else
            <tr>
                <td>No Existen Registros</td>
            </tr>
        @endif
    </table>
</div>
@push('scripts')
<script>
    $(document).ready(function(){
            $('#searchTraetment').on("keyup",function(){
                var value = $(this).val().toLowerCase();
                $('#tableData tr').filter(function(){
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
  function validar(evt)
  {
      var code = (evt.which) ? evt.which : evt.keyCode;
      if(code==8){
          return true;
      }else if(code>=48 && code<=57){
          return true;
      }else{
          return false;
      }
  }
</script>
@endpush
@endsection