routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');
Route::resource('customer','CustomerController')->middleware('auth');
Route::resource('bussiness','BussinessController')->middleware('auth');
Route::resource('provider','ProviderController')->middleware('auth');
Route::resource('sale','SaleController')->middleware('auth');
Route::resource('product','ProductController')->middleware('auth');
Route::resource('purchase','PurchaseController')->middleware('auth');
Route::resource('type_user','TypeUserController')->middleware('auth');
Route::resource('services','ServiceController')->middleware('auth');
Route::resource('operator','OperatorController')->middleware('auth');
Route::resource('quantity_session','QuantitySessionController')->middleware('auth');
Route::resource('typeTraetment','TypeTraetmentController')->middleware('auth');
Route::resource('traetment','TraetmentController')->middleware('auth');
Route::resource('sale_traetment','SaleTraetmentController')->middleware('auth');
Route::resource('traetment_process','TraetmentProcessController')->middleware('auth');
Route::resource('comision','CommissionController')->middleware('auth');
Route::resource('payment','PaymentController')->middleware('auth');
Route::resource('expense','ExpenseController')->middleware('auth');
Route::resource('users','UserController')->middleware('auth');

Route::get('event','EventController@index')->middleware('auth');
Route::get('cuadre','BoxController@cuadre_caja')->middleware('auth');
Route::get('listCuadre', 'BoxController@list_cuadre')->middleware('auth');
Route::get('descargar-venta/{id}','SaleController@imprimir');
Route::get('descargar-venta-tratamiento/{id}','SaleTraetmentController@imprimir');
Route::get('descargar-pago-tratamiento/{id}','SaleTraetmentController@pay');
Route::get('descargar-pago-venta/{id}','SaleTraetmentController@pay_sale');

Route::post('eventActividad','EventController@Ajax')->middleware('auth');
Route::resource('box','BoxController')->middleware('auth');

Route::get('cuadre_caja/{id}','BoxController@show_box')->name('mostrar');

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;

    protected $fillable = ['fullname','address','phone'];

    public function sale(){
        return $this->belongsTo('App\Models\Sale');
    }

    public function sale_traetments(){
        return $this->belongsTo('App\Models\SaleTraetment');
    }

    public function traetment_processes(){
        return $this->hasMany('App\Models\TraetmentProcess');
    }
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Customer;
use Illuminate\Http\Request;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $customers = Customer::all();
        return view('customer.index',compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        Customer::create($request->all());
        return redirect('customer');
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $customer = Customer::findOrFail($id);
        $customer->update($request->all());
        return redirect('customer');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $customer = Customer::findOrFail($id);
        $customer->delete();
        return redirect('customer');
    }
}

resources/views/customer/crear.blade.php
<div class="modal fade" id="createCustomer">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Cliente</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{route('customer.store')}}" method="post">
            @csrf
          <div class="mb-3">
            <label for="fullname" class="form-label">Nombre Completo</label>
            <input type="text" class="form-control" name="fullname" required>
          </div>
          <div class="mb-3">
            <label for="address" class="form-label">Dirección</label>
            <input type="text" class="form-control" name="address">
          </div>
          <div class="mb-3">
            <label for="phone" class="form-label">Teléfono</label>
            <input type="text" class="form-control" name="phone">
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
              <button class="btn btn-primary">Guardar</button>
          </div>
          
        </form>
      </div>
    </div>
  </div>
</div>

resources/views/customer/delete.blade.php
<div class="modal fade" id="modal-delete-{{$customer->id}}">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header bg-danger" >
                <h5 class="modal-title" id="exampleModalLabel">Cliente</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{{action('CustomerController@destroy',$customer->id)}}" method="POST">
                    @csrf
                    <input name="_method" type="hidden" value="DELETE">
                    <p>Confirma que desea eliminar al Cliente {{$customer->fullname}} </p>
                        
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <button class="btn btn-primary">Confirmar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/customer/edit.blade.php
<div class="modal fade" id="editCustomer-{{$customer->id}}">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-warning" >
        <h5 class="modal-title" id="exampleModalLabel">Cliente</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form action="{{route('customer.update',$customer->id)}}" method="post">
        <input name="_method" type="hidden" value="PATCH">
            @csrf
          <div class="mb-3">
            <label for="fullname" class="form-label">Nombre Completo</label>
            <input type="text" class="form-control" name="fullname" value="{{$customer->fullname}}">
          </div>
          <div class="mb-3">
            <label for="address" class="form-label">Dirección</label>
            <input type="text" class="form-control" name="address" value="{{$customer->address}}">
          </div>
          <div class="mb-3">
            <label for="phone" class="form-label">Teléfono</label>
            <input type="text" class="form-control" name="phone" value="{{$customer->phone}}">
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
              <button class="btn btn-primary">Editar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

resources/views/customer/index.blade.php
@extends('layouts.admin')
@section('content')
<div style="background: white">
    @include('customer.crear')
    <hr><h2 class="text-center">Listado de Clientes  <button data-bs-toggle="modal" data-bs-target="#createCustomer" class="btn btn-success rounded-circle text-white"><i class="fa fa-plus"></i></button></h2><hr>
    <input type="text" class="form-control" id="searchCustomer" placeholder="Cliente a Buscar...">
    <table class="table text-center" id="tableData">
        @if(isset($customers))
            <tr>
                <th>No.</th>
                <th>Nombre</th>
                <th>Dirección</th>
                <th>Teléfono</th>
                <th>Opciones</th>
            </tr>
            @foreach($customers as $customer)
                <tr>
                    <td>{{$loop->iteration}}</td>
                    <td>{{$customer->fullname}}</td>
                    <td>{{$customer->address}}</td>
                    <td>{{$customer->phone}}</td>
                    <td>
                        <a data-bs-toggle="modal" data-bs-target="#editCustomer-{{$customer->id}}" href="{{action('CustomerController@edit', $customer->id)}}"><button data-bs-toggle="tooltip" data-bs-placement="top" title="Editar" aria-hidden="true" class="btn btn-info"><i class="fas fa-edit" aria-hidden="true"></i></button></a>
                        <a data-bs-toggle="modal" data-bs-target="#modal-delete-{{$customer->id}}" data-toggle="modal"><button data-bs-toggle="tooltip" data-bs-placement="top" title="Eliminar" class="btn btn-danger"><i class="fa fa-times" aria-hidden="true"></i> </button></a>   
                    </td>
                </tr>
                @include('customer.edit')
                @include('customer.delete')
            @endforeach
        @else
            <tr>
                <td>No Existen Registros</td>
            </tr>
        @endif
    </table>
</div>
@endsection
@push('scripts')
<script>
    $(document).ready(function(){
        $('#searchCustomer').on("keyup",function(){
            var value = $(this).val().toLowerCase();
            $('#tableData tr').filter(function(){
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>
@endpush